---
hostname_fqdn: "{{ inventory_hostname }}"
hosts_map: "{
  '{{ ansible_default_ipv4.address }}': ['{{ project_influx_service_fqdn }}']
}"
project_ingress_address: "{{ ansible_em1['ipv4'][0]['address'] }}"

# use short delay in test environment
project_monit_start_delay: 5

project_mqtt_host: localhost
project_influxdb_host: "{{ project_ingress_address }}"
