---
sudo_configs:
  - name: 100_root
    content: |
      root ALL=(ALL) NOPASSWD: ALL
  - name: 200_vagrant
    content: |
      Defaults:vagrant !requiretty
      vagrant ALL=(ALL) NOPASSWD: ALL
influxdb_admin_username: admin
influxdb_admin_password: password
grafana_admin_user: admin
grafana_admin_password: password
project_grafana_influxdb_user: read
project_grafana_influxdb_password: password
project_telegraf_influxdb_user: telegraf
project_telegraf_influxdb_password: password
project_mqtt_user: dummy
project_mqtt_password: password
influxdb_users:
  - user_name: write
    user_password: password
    grants:
      - database: sensors
        privilege: WRITE
  - user_name: "{{ project_telegraf_influxdb_user }}"
    user_password: "{{ project_telegraf_influxdb_password }}"
    grants:
      - database: sensors
        privilege: WRITE
  - user_name: "{{ project_grafana_influxdb_user }}"
    user_password: "{{ project_grafana_influxdb_password }}"
    grants:
      - database: sensors
        privilege: READ
grafana_provisioning_files:
  - name: datasources/influxdb.yml
    state: present
    format: yaml
    content:
      apiVersion: 1
      datasources:
        - name: InfluxDB
          type: influxdb
          access: proxy
          database: sensors
          user: "{{ project_grafana_influxdb_user }}"
          password: "{{ project_grafana_influxdb_password }}"
          url: http://{{ influxdb_bind_address }}
          jsonData:
            httpMode: GET
