---
sudo_configs:
  - name: 100_root
    content: |
      root ALL=(ALL) NOPASSWD: ALL
  - name: 200_vagrant
    content: |
      Defaults:vagrant !requiretty
      vagrant ALL=(ALL) NOPASSWD: ALL
influxdb_admin_username: admin
influxdb_admin_password: password
grafana_admin_user: admin
grafana_admin_password: password
