---

- name: trombik.hosts
- name: trombik.hostname
- name: trombik.vim
- name: trombik.zsh
- name: trombik.git
- name: trombik.sudo
- name: trombik.user
- name: trombik.influxdb
- name: trombik.grafana
- name: trombik.nginx
- name: trombik.monit
- name: trombik.telegraf
- name: trombik.freebsd_pkg_repo
- name: trombik.apt_repo
- name: trombik.mosquitto
- name: trombik.tmux
- name: trombik.x509_certificate
- name: trombik.home_assistant
