---
all:
  hosts:
    nex1.i.trombik.org:
      ansible_host: nex1.i.trombik.org
  children:
    grafana:
      hosts:
        nex1.i.trombik.org:
    prod-credentials:
      children:
        grafana:
    prod:
      children:
        grafana:
