---
all:
  hosts:
    grafana2.i.trombik.org:
      ansible_host: grafana2.i.trombik.org
    mqtt2.i.trombik.org:
      ansible_host: mqtt2.i.trombik.org
  children:
    grafana:
      hosts:
        grafana2.i.trombik.org:
    mqtt:
      hosts:
        mqtt2.i.trombik.org:
    prod-credentials:
      children:
        grafana:
        mqtt:
    prod:
      children:
        grafana:
        mqtt:
