---
- hosts: grafana
  become: yes
  become_method: sudo
  environment:
    http_proxy: "{{ http_proxy | default() }}"
    https_proxy: "{{ https_proxy | default() }}"
    no_proxy: "{{ no_proxy | default() }}"

  pre_tasks:
    - debug: var=hostvars[inventory_hostname]
  roles:
    - role: trombik.hosts
    - role: trombik.hostname
    - role: trombik.vim
    - role: trombik.zsh
    - role: trombik.git
    - role: trombik.tmux
      when: ansible_os_family != 'OpenBSD'
    - role: trombik.sudo
    - role: trombik.user
    - role: trombik.influxdb
    - role: trombik.grafana
    - role: trombik.telegraf
    - role: trombik.nginx
    - role: trombik.home_assistant
    - role: trombik.monit
  vars:
